// <auto-generated />
using System;
using DoAn_ASP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAn_ASP.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DoAn_ASP.Models.BaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BaiViets");
                });

            modelBuilder.Entity("DoAn_ASP.Models.BinhLuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MaCTDT")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaCTDT");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("BinhLuans");
                });

            modelBuilder.Entity("DoAn_ASP.Models.ChiTietDienThoai", b =>
                {
                    b.Property<int>("MaCTDT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTDT"), 1L, 1);

                    b.Property<string>("BoNhoTrong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GiaTienBan")
                        .HasColumnType("int");

                    b.Property<string>("MaDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SLTK")
                        .HasColumnType("int");

                    b.HasKey("MaCTDT");

                    b.HasIndex("MaDT");

                    b.ToTable("ChiTietDienThoais");
                });

            modelBuilder.Entity("DoAn_ASP.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("MachiTietGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MachiTietGioHang"), 1L, 1);

                    b.Property<int>("MaCTDT")
                        .HasColumnType("int");

                    b.Property<int>("MaGioHang")
                        .HasColumnType("int");

                    b.Property<int>("SL")
                        .HasColumnType("int");

                    b.HasKey("MachiTietGioHang");

                    b.HasIndex("MaCTDT");

                    b.HasIndex("MaGioHang");

                    b.ToTable("ChiTietGioHangs");
                });

            modelBuilder.Entity("DoAn_ASP.Models.ChiTietHoaDonBan", b =>
                {
                    b.Property<string>("MaCTHDBan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GiaBan")
                        .HasColumnType("int");

                    b.Property<int>("MaCTDT")
                        .HasColumnType("int");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SL")
                        .HasColumnType("int");

                    b.HasKey("MaCTHDBan");

                    b.HasIndex("MaCTDT");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("ChiTietHoaDonBans");
                });

            modelBuilder.Entity("DoAn_ASP.Models.DanhGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("MaCTDT")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaCTDT");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("DoAn_ASP.Models.DiaChi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ChiTiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("huyen_id")
                        .HasColumnType("int");

                    b.Property<int>("tinh_id")
                        .HasColumnType("int");

                    b.Property<int>("xa_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiaChis");
                });

            modelBuilder.Entity("DoAn_ASP.Models.DienThoai", b =>
                {
                    b.Property<string>("MaDT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CameraSau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CameraTruoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GiaBanChung")
                        .HasColumnType("int");

                    b.Property<string>("HangSX")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeDieuHanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("ManHinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDT");

                    b.HasIndex("MaLoai");

                    b.ToTable("DienThoais");
                });

            modelBuilder.Entity("DoAn_ASP.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"), 1L, 1);

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.HasKey("MaGioHang");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("DoAn_ASP.Models.HoaDonBanHang", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TTDonHang")
                        .HasColumnType("bit");

                    b.Property<bool>("TTHuy")
                        .HasColumnType("bit");

                    b.Property<int>("TongTien")
                        .HasColumnType("int");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("HoaDonBanHangs");
                });

            modelBuilder.Entity("DoAn_ASP.Models.ImageDT", b =>
                {
                    b.Property<int>("STT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("STT"), 1L, 1);

                    b.Property<string>("ImgDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("STT");

                    b.HasIndex("MaDT");

                    b.ToTable("ImageDTs");
                });

            modelBuilder.Entity("DoAn_ASP.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"), 1L, 1);

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiSanPhams");
                });

            modelBuilder.Entity("DoAn_ASP.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"), 1L, 1);

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Isadmin")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("DoAn_ASP.Models.QuanHuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenHuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tinh_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuanHuyens");
                });

            modelBuilder.Entity("DoAn_ASP.Models.TinhThanhPho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TenTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TinhThanhPhos");
                });

            modelBuilder.Entity("DoAn_ASP.Models.XaPhuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Huyen_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("XaPhuongs");
                });

            modelBuilder.Entity("DoAn_ASP.Models.BinhLuan", b =>
                {
                    b.HasOne("DoAn_ASP.Models.ChiTietDienThoai", "ChiTietDienThoai")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaCTDT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_ASP.Models.NguoiDung", "NguoiDung")
                        .WithMany("BinhLuans")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietDienThoai");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAn_ASP.Models.ChiTietDienThoai", b =>
                {
                    b.HasOne("DoAn_ASP.Models.DienThoai", "DienThoai")
                        .WithMany("ChiTietDienThoais")
                        .HasForeignKey("MaDT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DienThoai");
                });

            modelBuilder.Entity("DoAn_ASP.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("DoAn_ASP.Models.ChiTietDienThoai", "ChiTietDienThoai")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaCTDT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_ASP.Models.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietDienThoai");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("DoAn_ASP.Models.ChiTietHoaDonBan", b =>
                {
                    b.HasOne("DoAn_ASP.Models.ChiTietDienThoai", "ChiTietDienThoai")
                        .WithMany("ChiTietHoaDonBans")
                        .HasForeignKey("MaCTDT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_ASP.Models.HoaDonBanHang", "HoaDonBanHang")
                        .WithMany("ChiTietHoaDonBans")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietDienThoai");

                    b.Navigation("HoaDonBanHang");
                });

            modelBuilder.Entity("DoAn_ASP.Models.DanhGia", b =>
                {
                    b.HasOne("DoAn_ASP.Models.ChiTietDienThoai", "ChiTietDienThoai")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaCTDT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_ASP.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietDienThoai");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAn_ASP.Models.DienThoai", b =>
                {
                    b.HasOne("DoAn_ASP.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany("DienThoais")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("DoAn_ASP.Models.GioHang", b =>
                {
                    b.HasOne("DoAn_ASP.Models.NguoiDung", "NguoiDung")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAn_ASP.Models.HoaDonBanHang", b =>
                {
                    b.HasOne("DoAn_ASP.Models.NguoiDung", "NguoiDung")
                        .WithMany("HoaDonBanHangs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DoAn_ASP.Models.ImageDT", b =>
                {
                    b.HasOne("DoAn_ASP.Models.DienThoai", "DienThoai")
                        .WithMany("ImageDTs")
                        .HasForeignKey("MaDT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DienThoai");
                });

            modelBuilder.Entity("DoAn_ASP.Models.ChiTietDienThoai", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("ChiTietHoaDonBans");

                    b.Navigation("DanhGias");
                });

            modelBuilder.Entity("DoAn_ASP.Models.DienThoai", b =>
                {
                    b.Navigation("ChiTietDienThoais");

                    b.Navigation("ImageDTs");
                });

            modelBuilder.Entity("DoAn_ASP.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("DoAn_ASP.Models.HoaDonBanHang", b =>
                {
                    b.Navigation("ChiTietHoaDonBans");
                });

            modelBuilder.Entity("DoAn_ASP.Models.LoaiSanPham", b =>
                {
                    b.Navigation("DienThoais");
                });

            modelBuilder.Entity("DoAn_ASP.Models.NguoiDung", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("DanhGias");

                    b.Navigation("GioHangs");

                    b.Navigation("HoaDonBanHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
